In [3]:
import pandas as pd
pd.__version__

'2.3.3'

In [4]:
#create dataframe
df= pd.DataFrame([1,2,3,4,5,6])
df

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [5]:
data = {
    'name' : ["vishal","aman","sanjay","vijay"],
    'age' : [26,36,4,52,],
    'Salary': [2000,300,400,550]
}
df = pd.DataFrame(data)
print(df)

     name  age  Salary
0  vishal   26    2000
1    aman   36     300
2  sanjay    4     400
3   vijay   52     550

In [6]:
#basic of dataframe understanding
df.head(2)#top
df.tail(2)#lower
df.shape#shape how many raws and colums
df.rename(columns={'Salary': 'monthly salary'},inplace=True)# resname columns

In [30]:
df

     name  age  monthly salary
0  vishal   26            2000
1    aman   36             300
2  sanjay    4             400
3   vijay   52             550

In [31]:
df.info

<bound method DataFrame.info of      name  age  monthly salary
0  vishal   26            2000
1    aman   36             300
2  sanjay    4             400
3   vijay   52             550>

In [7]:
df.to_csv('exmple data')# save datato csv if you dont want index valuedo this df.to-csv('example', index= Falsep)

In [8]:
newdf = pd.read_csv('exmple data')
newdf

   Unnamed: 0    name  age  monthly salary
0           0  vishal   26            2000
1           1    aman   36             300
2           2  sanjay    4             400
3           3   vijay   52             550

In [9]:
newdf[['name', 'age']]

     name  age
0  vishal   26
1    aman   36
2  sanjay    4
3   vijay   52

In [10]:
newdf.loc[df.name=='vishal']# selcet the row

   Unnamed: 0    name  age  monthly salary
0           0  vishal   26            2000

In [11]:
newdf.loc[(df.name=='vishal') & (newdf.age>18)]#select the raw with some filter

   Unnamed: 0    name  age  monthly salary
0           0  vishal   26            2000

In [12]:
#columns add/delete/
newdf['team']= ['CEO', 'MANAGER', 'ANALYST', 'ANALYST']
newdf

   Unnamed: 0    name  age  monthly salary     team
0           0  vishal   26            2000      CEO
1           1    aman   36             300  MANAGER
2           2  sanjay    4             400  ANALYST
3           3   vijay   52             550  ANALYST

In [13]:
newdf.loc[0, 'monthly salary']=2500 #update value
newdf

   Unnamed: 0    name  age  monthly salary     team
0           0  vishal   26            2500      CEO
1           1    aman   36             300  MANAGER
2           2  sanjay    4             400  ANALYST
3           3   vijay   52             550  ANALYST

In [14]:
newdf.drop(newdf[newdf.name=='vijay'].index, inplace= True)# delete raw

In [15]:
newdf.drop('team', axis =1)#colum delete

   Unnamed: 0    name  age  monthly salary
0           0  vishal   26            2500
1           1    aman   36             300
2           2  sanjay    4             400

In [16]:
newdf.sort_values('age')# shorting value  lower value to higher value

   Unnamed: 0    name  age  monthly salary     team
2           2  sanjay    4             400  ANALYST
0           0  vishal   26            2500      CEO
1           1    aman   36             300  MANAGER

In [18]:
#data value
newdf.sort_values('age', ascending = False)

   Unnamed: 0    name  age  monthly salary     team
1           1    aman   36             300  MANAGER
0           0  vishal   26            2500      CEO
2           2  sanjay    4             400  ANALYST

In [20]:
newdf['DOJ']= ['02/02/2020','10/12/2025','12/12/2023']
newdf

   Unnamed: 0    name  age  monthly salary     team         DOJ
0           0  vishal   26            2500      CEO  02/02/2020
1           1    aman   36             300  MANAGER  10/12/2025
2           2  sanjay    4             400  ANALYST  12/12/2023

In [23]:
newdf['DOJ'] = pd.to_datetime(newdf['DOJ'])
newdf['DOJ'].dtype#type cheak

dtype('<M8[ns]')

In [25]:
#missing value
import numpy as np
newdf.isnull()

   Unnamed: 0   name    age  monthly salary   team    DOJ
0       False  False  False           False  False  False
1       False  False  False           False  False  False
2       False  False  False           False  False  False

In [26]:
newdf.loc[newdf.name=='sanjay','age']= np.nan

In [27]:
newdf

   Unnamed: 0    name   age  monthly salary     team        DOJ
0           0  vishal  26.0            2500      CEO 2020-02-02
1           1    aman  36.0             300  MANAGER 2025-10-12
2           2  sanjay   NaN             400  ANALYST 2023-12-12

In [30]:
newdf.isnull().sum()

Unnamed: 0        0
name              0
age               1
monthly salary    0
team              0
DOJ               0
dtype: int64

In [31]:
newdf.fillna(0)

   Unnamed: 0    name   age  monthly salary     team        DOJ
0           0  vishal  26.0            2500      CEO 2020-02-02
1           1    aman  36.0             300  MANAGER 2025-10-12
2           2  sanjay   0.0             400  ANALYST 2023-12-12

In [38]:
#agrigation and group by
newdf['team'].value_counts()

team
CEO        1
MANAGER    1
ANALYST    1
Name: count, dtype: int64

In [41]:
newdf[newdf['monthly salary']==300].value_counts()

Unnamed: 0  name  age   monthly salary  team     DOJ
1           aman  36.0  300             MANAGER  2025-10-12    1
Name: count, dtype: int64

In [40]:
print(newdf.columns)

Index(['Unnamed: 0', 'name', 'age', 'monthly salary', 'team', 'DOJ'], dtype='object')

In [44]:
newdf.groupby('team')['monthly salary'].sum()

team
ANALYST     400
CEO        2500
MANAGER     300
Name: monthly salary, dtype: int64